# 根域名
origin: infra
# TTL
ttl: 10
# 云厂商
providers:
  # 名称，当前仅用于日志输出
  - name: 'Pagoda QCLOUD'
    # 厂商，支持厂商列表参见 README.md
    provider: qcloud
    # API 令牌
    token_id: xxxxxxxxxxxx
    token_secret: xxxxxxxxxxxx
    # 私有网络列表，必须填写，避免扫描到不应该扫描到的私有网络
    # 注意，不同厂商私有网络标识命名规范不同，参见各个厂商的文档
    networks:
      - region: ap-guangzhou
        id: vpc-xxxxx
    # 要扫描的服务，必须填写，一次性扫描全部服务代价太高
    # 注意，不同厂商服务标识命名不同，参见 README.md
    services:
      - cvm
      - cdb